### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by nuptwuchen** [Prinsphield/GeneGAN#2]
It is so slow，i do not know it will take how much time to train one expoch. I want to know, how long time I  finsih the train. gpu:Titanxp

**Comment by Prinsphield** [comment]
It took less than a day for 100000 iterations. To obtain better results, you may need more iterations. (Modify the `dataset.py` file.) 

The first iteration takes a longer time, since the discriminator was trained for 100 times for every 500 steps. 
[See here](https://github.com/Prinsphield/GeneGAN/blob/3c401f88cd97f06278d3f9638ee72b144551ac70/train.py#L66)

Besides, if training GeneGAN on a large scale distributed system, you'd better prepare tfrecords instead of images.

**Comment by nuptwuchen** [comment]
thank you

**Comment by nuptwuchen** [comment]
I found the problem that is my tensorflow version (1.0.0) is not correct. When i change it to (1.3.0    just pip install tensorflow-gpu), it all goes well.
